import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className="leading-normal tracking-normal text-indigo-400 m-6 bg-cover bg-fixed"
            style={{backgroundImage: "url('background.png')"}}>{children}</body>
        </html>
    );
}
